version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: next-saas_postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: next-saas
    ports:
      - "5432:5432"
