services:
  postgres:
    image: bitnami/postgresql:16
    container_name: db-next-saas-rbac
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: next-saas
    ports:
      - "5432:5432"
